# Server of the application
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
# Spring configuration to connect the database
spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/reservas_informatica # <- This database name or whatever you put
    username: root #input your username here
    password: root #input your password here
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
  logging:
    pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    level.org.hibernate.SQL: debug
    level: debug