swagger: '2.0'
host: localhost:8081
basePath: /aulas_informatica
info:
  version: 1.3.1
  title: TIC classroom based on Swagger
  description: This document shows the endpoints for add, modify or delete TIC classrooms data in a HTML web page
  contact:
    name: Manuel Canio Gil
    url: https://github.com/manuel-canio-gil-291
schemes:
- http
produces:
- text/html
paths:
  /:
    get: 
      operationId: paginaInicio
      responses:
        200:
          description: Returns the index web page that it gets the TIC clasroom data list
  /ver_formulario_nueva_aula:
    get:
      operationId: formularioNuevaAula
      responses:
        200:
          description: Returns a web page to add new TIC classroom data
  /ver_formulario_actualizar_aula/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      operationId: formularioActualizarAula
      responses:
        200:
          description: Returns a web page to update TIC classroom data corresponding the ID
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/TIC_classroom_error'
  /guardar_aula:
    post:
      parameters:
        - name: aula_informatica
          in: body
          required: true
          schema:
            $ref: '#/definitions/TIC_classroom'
      operationId: guardarDatosAulaInformatica
      responses:
        200:
          description: TIC Classroom data added successfully, redirect to the index
  /actualizar_aula/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: numero_aula
          in: header
          required: true
          type: integer
          format: int32
        - name: planta
          in: header
          required: true
          type: integer
          format: int32
      operationId: actualizarDatosAulaInformatica
      responses:
        200:
          description: TIC classroom data modified, redirect to the index
  /quitar_aula/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      operationId: deleteTICClassroomData
      responses:
        200:
          description: TIC classroom data deleted successfully, redirect to the index
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/TIC_classroom_error'


definitions:
  TIC_classroom:
    properties: 
      id:
        type: integer
        format: int64
        description: "The TIC classroom ID"
      numero_aula:
        type: integer
        format: int32
        description: "The classroom number"
      planta:
        type: integer
        format: int32
        description: "The floor that it's located"
  TIC_classroom_error:
    properties: 
      message:
        type: string