swagger: '2.0'
host: localhost:8081
basePath: /aulas_informatica
info:
  version: 1.2.0
  title: TIC classroom based on Swagger
  description: This document shows the endpoints for add, modify or delete TIC classrooms data
  contact:
    name: Manuel Canio Gil
    url: https://github.com/manuel-canio-gil-291
schemes:
- http
- https
paths:
  /:
    get: 
      operationId: getListTICClassroom
      responses:
        200:
          description: Query ok
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/TIC_classroom_error'
  /ver_formulario_nueva_aula:
    get:
      parameters:
        - name: numero_aula
          in: header
          required: true
          type: integer
          format: int32
        - name: planta
          in: header
          required: true
          type: integer
          format: int32
      operationId: formNewTICClassroom
      responses:
        200:
          description: Parameters ok
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/TIC_classroom_error'
  /ver_formulario_actualizar_aula/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: numero_aula
          in: header
          required: true
          type: integer
          format: int32
        - name: planta
          in: header
          required: true
          type: integer
          format: int32
      operationId: formUpdateTICClassroom
      responses:
        200:
          description: Parameters ok
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/TIC_classroom_error'
  /guardar_aula:
    post:
      parameters:
        - name: numero_aula
          in: header
          required: true
          type: integer
          format: int32
        - name: planta
          in: header
          required: true
          type: integer
          format: int32
      operationId: AddTICClassroomData
      responses:
        200:
          description: TIC Classroom data added successfully
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/TIC_classroom_error'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/TIC_classroom_error'
  /actualizar_aula/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: numero_aula
          in: header
          required: true
          type: integer
          format: int32
        - name: planta
          in: header
          required: true
          type: integer
          format: int32
      operationId: modifyTICClassroomData
      responses:
        200:
          description: TIC classroom data modified
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/TIC_classroom_error'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/TIC_classroom_error'
  /quitar_aula/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      operationId: deleteTICClassroomData
      responses:
        200:
          description: TIC classroom data deleted successfully
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/TIC_classroom_error'


definitions:
  TIC_classroom:
    properties: 
      id:
        type: integer
        format: int64
        description: "The TIC classroom ID"
      numero_aula:
        type: integer
        format: int32
        description: "The classroom number"
      planta:
        type: integer
        format: int32
        description: "The floor that it's located"
  TIC_classroom_error:
    properties: 
      code:
        type: integer
        format: int32
      message:
        type: string