swagger: '2.0'
host: localhost:8081
basePath: /carritos_tablets
info:
  title: Tablet trolleys based on Swagger
  description: This document shows the endpoints for add, modify or delete tablet trolleys data in a HTML web page
  version: 1.3.1
  contact:
    name: Manuel Canio Gil
    url: https://github.com/manuel-canio-gil-291
schemes:
- http
produces:
- text/html
paths:
  /:
    get:
      operationId: paginaInicio
      responses:
        200:
          description: Returns an index web page that get the tablet trolleys data list
  /ver_formulario_nuevo_carrito_tablets:
    get:
      operationId: formularioNuevoCarritoTablets
      responses:
        200:
          description: Returns a form to add new tablet trolley data
  /ver_formulario_actualizar_carrito_tablets/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: formularioActualizarCarritoTablets
      responses:
        200:
          description: Returns a form to update the tablet trolley data passing the ID
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Carrito_tablet_error'
  /guardar_carrito_tablets:
    parameters:
      - name: carrito_tablets
        in: body
        required: true
        schema:
          $ref: '#/definitions/Carrito_tablet'
    post:
      operationId: guardarCarritoTablets
      responses:
        200:
          description: Tablet trolley data added, redirect to the index page
  /actualizar_carrito_tablets/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: numero_Tablets
        in: header
        required: true
        type: integer
        format: int32
      - name: planta
        in: header
        required: true
        type: integer
        format: int32
    post:
      operationId: actualizarDatosCarritosTablets
      responses:
        200:
          description: Tablet trolley data updated, redirect to the index page
  /quitar_carrito_tablets/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: quitarCarritoTablets
      responses:
        200:
          description: Tablet trolley data deleted, redirect to the index page
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Carrito_tablet_error'

definitions:
  Carrito_tablet:
    properties: 
      id:
        type: integer
        format: int64
        description: "The Tablet trolley ID"
      numero_tablets:
        type: integer
        format: int32
        description: "The number of tablets"
      planta:
        type: integer
        format: int32
        description: "The floor that it's located"
  Carrito_tablet_error:
    properties:
      message:
        type: string