swagger: '2.0'
host: localhost:8081
basePath: /carritos_pcs
info:
  title: PC trolleys based on Swagger
  description: This document shows the endpoints for add, modify or delete PC trolleys data in a HTML web page
  version: 1.3.1
  contact:
    name: Manuel Canio Gil
    url: https://github.com/manuel-canio-gil-291
schemes:
- http
produces:
- text/html
paths:
  /:
    get:
      operationId: paginaInicio
      responses:
        200:
          description: Returns the index web page that get the PC trolleys data list
  /ver_formulario_nuevo_carrito_pcs:
    get:
      operationId: formularioNuevoCarritoPCs
      responses:
        200:
          description: Returns a form web page to add new PC trolley data 
  /ver_formulario_actualizar_carrito_pcs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: formularioActualizarCarritoPCs
      responses:
        200:
          description: Returns a form web page to update the PC trolley data corresponding the ID
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Carrito_PC_error'
  /guardar_carrito_pcs:
    parameters:
      - name: carrito_pc
        in: body
        required: true
        schema:
          $ref: '#/definitions/Carrito_PC'
    post:
      operationId: guardarDatosCarritoPCs
      responses:
        200:
          description: PC trolley data added, redirect to the index page
  /actualizar_carrito_pcs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: numero_pcs
        in: header
        required: true
        type: integer
        format: int32
      - name: planta
        in: header
        required: true
        type: integer
        format: int32
      - name: sistema_operativo
        in: header
        required: false
        type: string
    post:
      operationId: actualizarDatosCarritosPCs
      responses:
        200:
          description: PC trolley data updated, redirect to the index page
  /quitar_carrito_pcs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: quitarCarritoPCs
      responses:
        200:
          description: PC trolley data deleted, redirect to the index page
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Carrito_PC_error'

definitions:
  Carrito_PC:
    properties: 
      id:
        type: integer
        format: int64
        description: "The PC trolley ID"
      numero_pcs:
        type: integer
        format: int32
        description: "The number of PCs"
      planta:
        type: integer
        format: int32
        description: "The floor that it's located"
      sistema_operativo:
        type: string
        description: "The operating system installed"
  Carrito_PC_error:
    properties:
      message:
        type: string