swagger: '2.0'
host: localhost:8081
basePath: /profesores
info:
  title: Teachers based on Swagger
  description: This document shows the endpoints for add, modify or delete teachers data in a HTML web page
  version: 1.3.1
  contact:
    name: Manuel Canio Gil
    url: https://github.com/manuel-canio-gil-291
schemes:
- http
produces:
- text/html
paths:
  /:
    get:
      operationId: paginaInicio
      responses:
        200:
          description: Returns the index page that get the teachers data list
  /ver_formulario_nuevo_profesor:
    get:
      operationId: formularioNuevoProfesor
      responses:
        200:
          description: Returns a form to add new teacher data
  /ver_formulario_actualizar_profesor/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      operationId: formularioActualizarProfesor
      responses:
        200:
          description: Returns a form to update the teacher data passing the id
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Teacher_error'
  /guardar_profesor:
    post:
      parameters:
        - name: profesor
          in: body
          required: true
          schema:
            $ref: '#/definitions/Teacher'
      operationId: guardarDatosProfesor
      responses:
        200:
          description: Teacher data added successfully, redirect to the index page
  /actualizar_profesor/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: nombre
          in: header
          required: true
          type: string
        - name: apellidos
          in: header
          required: true
          type: string
      operationId: actualizarDatosProfesor
      responses:
        200:
          description: Teacher data modified, redirect to the index page
  /quitar_profesor/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      operationId: quitarProfesor
      responses:
        200:
          description: Teacher data deleted, redirect to the index page
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Teacher_error'


definitions:
  Teacher:
    properties: 
      id:
        type: integer
        format: int64
        description: "The teacher ID"
      nombre:
        type: string
        description: "The name of the teacher"
      apellidos:
        type: string
        description: "The surname of the teacher"
  Teacher_error:
    properties: 
      message:
        type: string
  