swagger: '2.0'
host: localhost:8081
basePath: /reservas
info:
  version: 1.3.1
  title: Reservation based on Swagger
  description: This document shows the endpoints for add, modify or delete a reservation in a HTML web page
  contact:
    name: Manuel Canio Gil
    url: https://github.com/manuel-canio-gil-291
schemes:
- http
produces:
- text/html
paths:
  /:
    get:
      operationId: paginaInicioReservas
      responses:
        200:
          description: Returns the index page that get all the reservations of the classrooms and trolleys
  /formulario_nueva_reserva_aula:
    get:
      operationId: formularioNuevaReservaAula
      responses:
        200:
          description: Returns a form to add a new classroom reservation
  /formulario_nueva_reserva_carrito_pcs:
    get:
      operationId: formularioNuevaReservaCarritoPCs
      responses:
        200:
          description: Returns a form to add a new PC trolley reservation
  /formulario_nueva_reserva_carrito_tablets:
    get:
      operationId: formularioNuevaReservaCarritoTablets
      responses:
        200:
          description: Returns a form to add a new tablet trolley reservation
  /guardar_reserva_aula:
    parameters:
      - name: reserva_aula
        in: body
        required: true
        schema:
          $ref: '#/definitions/TIC_classroom_reservation'
    post:
      operationId: guardarReservaAula
      responses:
        200:
          description: Classroom reservation added, redirect to the index page
        500:
          description: Conflict with the date of the reservation
          schema:
            $ref: '#/definitions/Reservation_error'
  /guardar_reserva_carrito_pcs:
    parameters:
      - name: reserva_carrito_pcs
        in: body
        required: true
        schema:
          $ref: '#/definitions/PC_trolleys_reservation'
    post:
      operationId: guardarReservaCarritoPCs
      responses:
        200:
          description: PC trolley reservation added, redirect to the index page
        500:
          description: Conflict with the date of the reservation
          schema:
            $ref: '#/definitions/Reservation_error'
  /guardar_reserva_carrito_tablets:
    parameters:
      - name: reserva_carrito_tablets
        in: body
        required: true
        schema:
          $ref: '#/definitions/Tablet_trolleys_reservation'
    post:
      operationId: guardarReservaCarritoTablets
      responses:
        200:
          description: Tablet trolley reservation added, redirect to the index page
        500:
          description: Conflict with the date of the reservation
          schema:
            $ref: '#/definitions/Reservation_error'
  /formulario_actualizar_reserva_aula/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: formularioActualizarReservaAula
      responses:
        200:
          description: Returns a form to update the classroom reservation corresponding the ID
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Reservation_error'
  /formulario_actualizar_reserva_carrito_pcs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: formularioActualizarReservaCarritoPCs
      responses:
        200:
          description: Returns a form to update the PC trolley reservation corresponding the ID
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Reservation_error'
  /formulario_actualizar_reserva_carrito_tablets/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: formularioActualizarReservaCarritoTablets
      responses:
        200:
          description: Returns a form to update the tablet trolley reservation corresponding the ID
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Reservation_error'
  /actualizar_reserva_aula/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: idProfesor
        in: header
        required: true
        type: integer
        format: int64
      - name: idAula
        in: header
        required: true
        type: integer
        format: int64
      - name: fecha
        in: header
        required: true
        type: string
    post:
      operationId: actualizarReservaAula
      responses:
        200:
          description: Classroom reservation updated, redirect to the index page
  /actualizar_reserva_carrito_pcs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: idProfesor
        in: header
        required: true
        type: integer
        format: int64
      - name: idCarritoPcs
        in: header
        required: true
        type: integer
        format: int64
      - name: ubicacion_prestamo
        in: header
        required: false
        type: string
      - name: date
        in: header
        required: true
        type: string
    post:
      operationId: actualizarReservaCarritoPCs
      responses:
        200:
          description: PC trolley reservation updated, redirect to the index page
  /actualizar_reserva_carrito_tablets/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: idProfesor
        in: header
        required: true
        type: integer
        format: int64
      - name: idCarritoPcs
        in: header
        required: true
        type: integer
        format: int64
      - name: ubicacion_prestamo
        in: header
        required: false
        type: string
      - name: date
        in: header
        required: true
        type: string
    post:
      operationId: actualizarReservaCarritoTablets
      responses:
        200:
          description: Tablet trolley reservation updated, redirect to the index page
  /anular_reserva_aula/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: anularReservaAula
      responses:
        200:
          description: Classroom reservation deleted, redirect to the index page
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Reservation_error'
  /anular_reserva_carrito_pcs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: anularReservaCarritoPCs
      responses:
        200:
          description: PC trolley reservation deleted, redirect to the index page
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Reservation_error'
  /anular_reserva_carrito_tablets/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: anularReservaCarritoTablets
      responses:
        200:
          description: Tablet trolley reservation deleted, redirect to the index page
        500:
          description: Invalid ID value
          schema:
            $ref: '#/definitions/Reservation_error'

definitions:
  TIC_classroom_reservation:
    properties: 
      id:
        type: integer
        format: int64
        description: "The reservation ID"
      idProfesor:
        type: integer
        format: int64
        description: "The teacher ID"
      idAula:
        type: integer
        format: int64
        description: "The classroom ID"
      fecha:
        type: string
        description: "The date of the reservation"
  PC_trolleys_reservation:
    properties: 
      id:
        type: integer
        format: int64
        description: "The reservation ID"
      idProfesor:
        type: integer
        format: int64
        description: "The teacher ID"
      idCarritoPcs:
        type: integer
        format: int64
        description: "The PC trolley ID"
      ubicacion_prestamo:
        type: string
        description: "The loan location"
      date:
        type: string
        description: "The date of the reservation"
  Tablet_trolleys_reservation:
    properties: 
      id:
        type: integer
        format: int64
        description: "The reservation ID"
      idProfesor:
        type: integer
        format: int64
        description: "The teacher ID"
      idCarritoTablets:
        type: integer
        format: int64
        description: "The tablet trolley ID"
      ubicacion_prestamo:
        type: string
        description: "The loan location"
      date:
        type: string
        description: "The date of the reservation"
  Reservation_error:
    properties:
      message:
        type: string
